# PCA on quality group

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('winequalityN.csv')
#df = df.fillna(0)

In [2]:
def myfunction(x):
    if x == "red":
        return 0
    else:#white
        return 1
    
    
df["type"] = df["type"].apply(myfunction)

In [3]:
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,1,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,1,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
def null_cell(df): 
    total_missing_values = df.isnull().sum() 
    missing_values_per = df.isnull().sum()/df.isnull().count() 
    null_values = pd.concat([total_missing_values, missing_values_per], axis=1, keys=['total_null', 'total_null_perc']) 
    null_values = null_values.sort_values('total_null', ascending=False) 
    return null_values[null_values['total_null'] > 0]

fill_data = (null_cell(df)).index
print(fill_data)

df_new = df.copy()
for col in fill_data:
    df_new.loc[:, col].fillna(df_new.loc[:, col].mean(), inplace=True)
     #df_new.loc[:, col].fillna(0)

#Checking for NULL Values
Sum = df.isnull().sum()
percentage = (df.isnull().sum()/df.isnull().count())
pd.concat([Sum,percentage], axis =1, keys= ['Sum', 'Percentage'])

Index(['fixed acidity', 'pH', 'volatile acidity', 'sulphates', 'citric acid',
       'residual sugar', 'chlorides'],
      dtype='object')

                      Sum  Percentage
type                    0    0.000000
fixed acidity          10    0.001539
volatile acidity        8    0.001231
citric acid             3    0.000462
residual sugar          2    0.000308
chlorides               2    0.000308
free sulfur dioxide     0    0.000000
total sulfur dioxide    0    0.000000
density                 0    0.000000
pH                      9    0.001385
sulphates               4    0.000616
alcohol                 0    0.000000
quality                 0    0.000000

In [5]:
df_new.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,1,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,1,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [6]:
#binning
df_bins = df_new.copy()
print(df.shape)

bins = [0,4,7,10]

labels = [0,1,2] 

df_bins['quality_range'] = pd.cut(x = df_bins['quality'], bins = bins, labels = labels)

(6497, 13)

In [8]:
x = StandardScaler().fit_transform(df_bins.iloc[:,:12])
print(x)
y = df_bins['quality_range']
print(y)


pca = PCA(n_components=5)
pc = pca.fit_transform(x)

print(pca.explained_variance_ratio_)
print(pca.explained_variance_ratio_.sum())

[[ 0.57136659 -0.1671586  -0.4235636  ... -1.35966451 -0.5459591
  -1.41855821]
 [ 0.57136659 -0.70742728 -0.24123152 ...  0.50804501 -0.27706392
  -0.83161516]
 [ 0.57136659  0.68183504 -0.36278624 ...  0.25901707 -0.6131829
  -0.32852111]
 ...
 [-1.75018984 -0.70742728  1.03509307 ...  1.25512882  1.47075478
   0.42611996]
 [-1.75018984 -1.01615224  1.85558744 ...  2.18898358  1.2018596
  -0.2446721 ]
 [-1.75018984 -0.938971   -0.18045416 ...  1.06835787  0.86574062
   0.42611996]]
0       1
1       1
2       1
3       1
4       1
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: quality_range, Length: 6497, dtype: category
Categories (3, int64): [0 < 1 < 2]
[0.31741069 0.21070355 0.129986   0.08097186 0.06033924]
0.7994113430791155